version: '3.4'
services:
  # compile static assets using Webpack.
  assets:
    build:
      context: .
      target: assets
    image: mozmeao/bedrock_assets:${GIT_COMMIT:-latest}
    command: npm run watch
    volumes:
      - ./media/:/app/media:delegated
      - assets_volume:/app/assets

  # the django app
  app:
    build:
      context: .
      target: devapp
    image: mozmeao/bedrock_test:${GIT_COMMIT:-latest}
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./bedrock/:/app/bedrock:delegated
      - ./bin/:/app/bin:delegated
      - ./docker/:/app/docker:delegated
      - ./etc/:/app/etc:delegated
      - ./lib/:/app/lib:delegated
      - ./docs/:/app/docs:delegated
      - ./media/:/app/media:delegated
      - ./root_files/:/app/root_files:delegated
      - ./scripts/:/app/scripts:delegated
      - ./vendor-local/:/app/vendor-local:delegated
      - ./wsgi/:/app/wsgi:delegated
      - ./locale/:/app/locale:delegated
      - ./l10n/:/app/l10n:delegated
      - ./git-repos/:/app/git-repos:delegated
      - assets_volume:/app/assets

  # run the tests against local changes
  test:
    image: mozmeao/bedrock_test:${GIT_COMMIT:-latest}
    env_file: docker/envfiles/test.env
    volumes:
      - ./bedrock/:/app/bedrock:delegated
      - ./bin/:/app/bin:delegated
      - ./docker/:/app/docker:delegated
      - ./etc/:/app/etc:delegated
      - ./lib/:/app/lib:delegated
      - ./media/:/app/media:delegated
      - ./root_files/:/app/root_files:delegated
      - ./scripts/:/app/scripts:delegated
      - ./tests/:/app/tests:delegated
      - ./vendor-local/:/app/vendor-local:delegated
      - ./wsgi/:/app/wsgi:delegated
      - ./l10n/:/app/l10n:delegated
      - ./git-repos/:/app/git-repos:delegated

  # run tests with no volumes
  test-image:
    image: mozmeao/bedrock_test:${GIT_COMMIT:-latest}
    env_file: docker/envfiles/test.env

  # the django app
  release:
    build:
      context: .
      target: release
      args:
        GIT_SHA: ${GIT_COMMIT:-latest}
        BRANCH_NAME: ${BRANCH_NAME:-latest}
    image: mozmeao/bedrock:${BRANCH_AND_COMMIT:-latest}

  release-local:
    image: mozmeao/bedrock:${BRANCH_AND_COMMIT:-latest}
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./bedrock/:/app/bedrock:delegated
      - ./bin/:/app/bin:delegated
      - ./docker/:/app/docker:delegated
      - ./etc/:/app/etc:delegated
      - ./lib/:/app/lib:delegated
      - ./root_files/:/app/root_files:delegated
      - ./scripts/:/app/scripts:delegated
      - ./vendor-local/:/app/vendor-local:delegated
      - ./wsgi/:/app/wsgi:delegated
      - ./locale/:/app/locale:delegated
      - ./l10n/:/app/l10n:delegated
      - ./git-repos/:/app/git-repos:delegated

  builder:
    build:
      context: .
      target: python-builder
    image: mozmeao/bedrock_build:${GIT_COMMIT:-latest}

  app-base:
    build:
      context: .
      target: app-base
    image: mozmeao/bedrock_code:${GIT_COMMIT:-latest}

volumes:
  assets_volume:
